[package]
name = "graph_test"
version = "0.1.0"
edition = "2021"
license-file = "./LICENSE"
authors = ["Domenic Melcher <domi.m@outlook.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
petgraph = "0.6.3"
